version: "2.4"

services:

    wallet_server:
      container_name: wallet_server
      image: golang:1.16
      ports:
        - "8080:8080"
      command: 
        - /bin/bash 
        - -c 
        - |
          go run section3/servers/wallet/main.go -gateway http://blockchain_1_server:5000
      volumes:
        - .:/var/project
      working_dir: /var/project

    blockchain_1_server:
      container_name: blockchain_1_server
      image: golang:1.16
      ports:
        - "5000:5000"
      command: 
        - /bin/bash 
        - -c 
        - |
          go run section3/servers/blockchain/main.go
      volumes:
        - .:/var/project
      working_dir: /var/project