version: "2.4"

services:
    # ganache:
    #   container_name: ganache
    #   image: trufflesuite/ganache-core
    #   ports:
    #     - "8545:8545"
    geth:
      container_name: geth
      image: ethereum/client-go:alltools-stable
      ports:
        - "8545:8545"
        - "8546:8546"
        - "8547:8547"
        - "30303:30303"
      working_dir: /var/app
      volumes:
        - ./go-ethereum:/root/.ethereum
        - ./ex_private_network:/var/app/ex_private_network
      command:
        - /bin/sh 
        - -c 
        - |
          tail -f /dev/null
    node:
      container_name: node
      build: 
        context: .
        dockerfile: ./web3.dockerfile
      ports:
        - "3000:3000"
        - "9545:9545"
      command: 
        - /bin/bash 
        - -c 
        - |
          tail -f /dev/null
      volumes:
        - .:/var/project
      working_dir: /var/project
      environment:
        NODE_OPTIONS: --openssl-legacy-provider